# Generated by Django 6.0.6 on 2026-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0002_alter_event_date_alter_event_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Location Principale', max_length=200),
        ),
    ]
