# Generated by Django 6.0.6 on 2026-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero telefono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee')], default='attendee', max_length=20, verbose_name='Ruolo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Indirizzo Email'),
        ),
    ]
